### ISSUE TITLE
Improve Container permissions

### ISSUE THREAD

**Issue by basti481** [codeformuenster/muenster-jetzt#87]
Not for this PR but maybe worth thinking about running all application containers with lowered permissions (not root, etc) like this

```yaml
    cap_drop:
      - ALL
    security_opt:
      - no-new-privileges=true
    read_only: true
    tmpfs:
      - /tmp
```

and maybe an user with lowered permissions

_Originally posted by @ubergesundheit in https://github.com/codeformuenster/muenster-jetzt/pull/77#issuecomment-668534491_
